"""Load, classify, split and write subtitle files."""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Collection, Sequence
from pathlib import Path
from typing import Final

import pysubs2
from pysubs2 import SSAEvent, SSAFile

from anishift.errors import ErrorCode, ErrorContext
from anishift.services.subtitles.classifier import Category, StyleVerdict, classify_styles
from anishift.services.subtitles.errors import SubtitleError
from anishift.services.subtitles.text import is_drawing, replace_visible_text, visible_text
from anishift.services.subtitles.types import (
    Decision,
    SplitStats,
    SpokenLine,
    SubtitleKind,
    SubtitleSplit,
)
from anishift.utils.logger import get_logger

__all__ = [
    "collapse_fbf",
    "load_subtitles",
    "preview_styles",
    "split_subtitles",
    "subtitle_kind",
    "write_displayed",
    "write_full",
    "write_spoken",
    "write_translated",
    "write_translated_displayed",
    "write_translated_spoken",
]

# ── Constants ─────────────────────────────────────────────────────────────────

_FBF_MAX_GAP_MS: Final[int] = 500
"""Maximum gap between consecutive identical events merged as one FBF run."""

_SAMPLES_PER_STYLE: Final[int] = 3
"""Number of preview samples collected per style."""

_SAMPLE_MAX_CHARS: Final[int] = 60
"""Maximum preview sample length."""

_SUFFIX_KIND: Final[dict[str, SubtitleKind]] = {".ass": "ass", ".ssa": "ass", ".srt": "srt"}
"""Supported subtitle suffixes and their working formats."""

_ENCODING: Final[str] = "utf-8"
"""Subtitle file encoding."""

_LINE_BREAKS: Final[dict[SubtitleKind, str]] = {"ass": "\\N", "srt": "\n"}
"""Soft line break joining a displayed event's verses, per subtitle format."""

_NOTICE_URL: Final[str] = "https://github.com/MattyMroz/AniShift"
"""Project URL written into the Script Info notice of generated ASS files."""

logger = get_logger(__name__)


def _header_notice() -> str:
    """Return the ``Script Info`` notice stamped into generated ASS files."""
    from importlib.metadata import PackageNotFoundError, version  # noqa: PLC0415 - metadata read only on write

    try:
        tag = f"v{version('anishift')}"
    except PackageNotFoundError:
        tag = "dev"
    return f"Script generated by AniShift {tag}\n{_NOTICE_URL}"


def _fail(code: ErrorCode, message: str) -> SubtitleError:
    return SubtitleError(context=ErrorContext(code=code, message=message))


def subtitle_kind(path: Path) -> SubtitleKind | None:
    """Return the working format for a file suffix, or None when unsupported."""
    return _SUFFIX_KIND.get(path.suffix.lower())


def load_subtitles(path: Path) -> SSAFile:
    """Load a subtitle file in UTF-8.

    Raises:
        SubtitleError: When the file is missing, unreadable or unparsable.
    """
    try:
        subtitles: SSAFile = pysubs2.load(str(path), encoding=_ENCODING)
    except FileNotFoundError as exc:
        msg = f"Subtitle file not found: {path}"
        raise _fail(ErrorCode.SUBTITLE_PARSE_FAILED, msg) from exc
    except UnicodeDecodeError as exc:
        msg = f"Subtitle file is not valid UTF-8: {path}"
        raise _fail(ErrorCode.SUBTITLE_PARSE_FAILED, msg) from exc
    except OSError as exc:
        msg = f"Subtitle file could not be read: {path}"
        raise _fail(ErrorCode.SUBTITLE_PARSE_FAILED, msg) from exc
    except pysubs2.exceptions.Pysubs2Error as exc:
        msg = f"Subtitle file could not be parsed: {path}"
        raise _fail(ErrorCode.SUBTITLE_PARSE_FAILED, msg) from exc
    logger.debug(
        "Subtitle file loaded",
        source=path.name,
        event_count=len(subtitles.events),
        style_count=len(subtitles.styles),
    )
    return subtitles


def preview_styles(subs: SSAFile) -> tuple[tuple[StyleVerdict, ...], dict[str, tuple[str, ...]]]:
    """Classify styles and collect short, visible-text samples per style."""
    verdicts = tuple(classify_styles(subs))
    samples: dict[str, list[str]] = defaultdict(list)
    for event in subs.events:
        if event.type != "Dialogue" or is_drawing(event.text):
            continue
        text = visible_text(event.text)
        if not text or text in samples[event.style] or len(samples[event.style]) >= _SAMPLES_PER_STYLE:
            continue
        samples[event.style].append(text[: _SAMPLE_MAX_CHARS - 1] + "…" if len(text) > _SAMPLE_MAX_CHARS else text)
    return verdicts, {style: tuple(lines) for style, lines in samples.items()}


def _make_run(events: list[tuple[int, SSAEvent]], text: str, style: str) -> SpokenLine:
    raw_events = [event for _, event in events]
    return SpokenLine(
        start=min(event.start for event in raw_events),
        end=max(event.end for event in raw_events),
        text=text,
        style=style,
        order=min(order for order, _ in events),
    )


def _collapse_group(
    events: list[tuple[int, SSAEvent]],
    text: str,
    style: str,
) -> tuple[list[SpokenLine], int]:
    ordered = sorted(events, key=lambda item: item[1].start)
    runs: list[list[tuple[int, SSAEvent]]] = []
    for item in ordered:
        event = item[1]
        if not runs or event.start - max(run_event.end for _, run_event in runs[-1]) > _FBF_MAX_GAP_MS:
            runs.append([item])
            continue
        runs[-1].append(item)
    return [_make_run(run, text, style) for run in runs], len(events) - len(runs)


def collapse_fbf(events: Sequence[SSAEvent]) -> tuple[tuple[SpokenLine, ...], int]:
    """Collapse frame-by-frame runs of identical visible text."""
    return _collapse_fbf_indexed(tuple(enumerate(events)))


def _collapse_fbf_indexed(
    events: Sequence[tuple[int, SSAEvent]],
) -> tuple[tuple[SpokenLine, ...], int]:
    """Collapse indexed frame events while retaining source-file order."""
    groups: dict[tuple[str, str], list[tuple[int, SSAEvent]]] = defaultdict(list)
    for order, event in events:
        if is_drawing(event.text):
            continue
        text = visible_text(event.text)
        if text:
            groups[(event.style, text)].append((order, event))
    lines: list[SpokenLine] = []
    collapsed_away = 0
    for (style, text), group in groups.items():
        group_lines, removed = _collapse_group(group, text, style)
        lines.extend(group_lines)
        collapsed_away += removed
    lines.sort(key=lambda line: (line.order, line.start, line.end, line.style))
    return tuple(lines), collapsed_away


def _dialogue_decisions(
    dialogue: Sequence[SSAEvent],
    spoken_styles: Collection[str],
) -> tuple[list[Decision], int, int, int]:
    decisions: list[Decision] = []
    drawing_events = 0
    for event in dialogue:
        if is_drawing(event.text):
            decisions.append("displayed")
            drawing_events += 1
            continue
        decisions.append("spoken" if event.style in spoken_styles else "displayed")
    spoken_events = decisions.count("spoken")
    if spoken_events == 0 and len(dialogue) > drawing_events:
        decisions = ["displayed" if is_drawing(event.text) else "spoken" for event in dialogue]
        spoken_events = len(dialogue) - drawing_events
    return decisions, spoken_events, drawing_events, decisions.count("displayed")


def split_subtitles(
    subs: SSAFile,
    *,
    kind: SubtitleKind,
    spoken_styles: Collection[str] | None = None,
    verdicts: Sequence[StyleVerdict] | None = None,
) -> SubtitleSplit:
    """Mark every Dialogue line spoken or displayed and build the spoken stream."""
    dialogue = [event for event in subs.events if event.type == "Dialogue"]
    if kind == "srt":
        decisions: list[Decision] = ["spoken"] * len(dialogue)
        final_verdicts: tuple[StyleVerdict, ...] = ()
        drawing_events = 0
    else:
        final_verdicts = tuple(verdicts) if verdicts is not None else tuple(classify_styles(subs))
        styles = (
            set(spoken_styles)
            if spoken_styles is not None
            else {verdict.style for verdict in final_verdicts if verdict.category is Category.DIALOG}
        )
        decisions, _, drawing_events, _ = _dialogue_decisions(dialogue, styles)
    spoken_events = decisions.count("spoken")
    spoken_input = [
        (order, event)
        for order, (event, decision) in enumerate(zip(dialogue, decisions, strict=True))
        if decision == "spoken"
    ]
    spoken, collapsed_away = _collapse_fbf_indexed(spoken_input)
    stats = SplitStats(
        total_events=len(dialogue),
        spoken_events=spoken_events,
        spoken_lines=len(spoken),
        displayed_events=decisions.count("displayed"),
        drawing_events=drawing_events,
        collapsed_away=collapsed_away,
    )
    logger.info(
        "Subtitles classified",
        kind=kind,
        total_events=stats.total_events,
        spoken_events=stats.spoken_events,
        displayed_events=stats.displayed_events,
        drawing_events=stats.drawing_events,
        collapsed_events=stats.collapsed_away,
    )
    return SubtitleSplit(kind, subs, tuple(decisions), final_verdicts, spoken, stats)


def _stream_file(split: SubtitleSplit, selected: Decision | None) -> SSAFile:
    out = SSAFile()
    out.info = dict(split.subs.info)
    out.styles = {name: style.copy() for name, style in split.subs.styles.items()}
    dialogue_index = 0
    for event in split.subs.events:
        if event.type != "Dialogue":
            out.events.append(event)
            continue
        if selected is None or split.decisions[dialogue_index] == selected:
            out.events.append(event)
        dialogue_index += 1
    return out


def _write_output(output: SSAFile, dest: Path, kind: SubtitleKind, *, subject: str) -> Path:
    temporary = dest.with_name(dest.name + ".tmp")
    try:
        temporary.write_text(output.to_string(format_=kind, header_notice=_header_notice()), encoding=_ENCODING)
        temporary.replace(dest)
    except OSError as exc:
        msg = f"{subject} subtitles could not be written: {dest}"
        raise _fail(ErrorCode.IO_ERROR, msg) from exc
    logger.debug(
        "Subtitle product written",
        product=subject,
        destination=dest.name,
        event_count=len(output.events),
    )
    return dest


def write_full(split: SubtitleSplit, dest: Path) -> Path | None:
    """Write the complete source subtitle product atomically, or None when empty."""
    if split.stats.total_events == 0:
        return None
    return _write_output(_stream_file(split, None), dest, split.kind, subject="Complete")


def write_spoken(split: SubtitleSplit, dest: Path) -> Path | None:
    """Write the source spoken-only product atomically, or None when empty."""
    if split.stats.spoken_events == 0:
        return None
    return _write_output(_stream_file(split, "spoken"), dest, split.kind, subject="Spoken")


def write_displayed(split: SubtitleSplit, dest: Path) -> Path | None:
    """Write the displayed product atomically, or return None when empty."""
    if split.stats.displayed_events == 0:
        return None
    return _write_output(_stream_file(split, "displayed"), dest, split.kind, subject="Displayed")


def _translated_file(
    split: SubtitleSplit,
    displayed_verses: Sequence[tuple[str, ...]],
    spoken_verses: Sequence[tuple[str, ...]],
    *,
    selected: Decision | None = None,
) -> SSAFile:
    out = SSAFile()
    out.info = dict(split.subs.info)
    out.styles = {name: style.copy() for name, style in split.subs.styles.items()}
    line_break = _LINE_BREAKS[split.kind]
    translated_spoken = tuple(zip(split.spoken, spoken_verses, strict=True)) if selected in {None, "spoken"} else ()
    spoken_by_key: defaultdict[tuple[str, str], list[tuple[SpokenLine, tuple[str, ...]]]] = defaultdict(list)
    for spoken, translated in translated_spoken:
        spoken_by_key[spoken.style, spoken.text].append((spoken, translated))
    dialogue_index = 0
    displayed_index = 0
    for event in split.subs.events:
        if event.type != "Dialogue":
            out.events.append(event)
            continue
        decision = split.decisions[dialogue_index]
        dialogue_index += 1
        if selected is not None and decision != selected:
            continue
        if decision == "displayed":
            if is_drawing(event.text):
                verses: tuple[str, ...] | None = None
            else:
                verses = displayed_verses[displayed_index]
                displayed_index += 1
        else:
            visible = visible_text(event.text)
            verses = next(
                (
                    translated
                    for spoken, translated in spoken_by_key.get((event.style, visible), ())
                    if spoken.start <= event.start and event.end <= spoken.end
                ),
                None,
            )
        if verses is None:
            out.events.append(event)
            continue
        replaced = event.copy()
        replaced.text = replace_visible_text(event.text, line_break.join(verses))
        out.events.append(replaced)
    return out


def write_translated(
    split: SubtitleSplit,
    displayed_verses: Sequence[tuple[str, ...]],
    spoken_verses: Sequence[tuple[str, ...]],
    dest: Path,
) -> Path | None:
    r"""Write the whole translated subtitle file atomically, or None when empty.

    Every Dialogue event is kept - spoken and displayed alike - with its tags,
    style and timing intact; only the visible text is replaced with translated
    verses joined by the format's soft break (``\N`` for ASS, ``\n`` for SRT).

    Args:
        split: The split whose source file is re-assembled.
        displayed_verses: One verse tuple per non-drawing displayed event, in
            event order. Vector drawings are copied without consuming a tuple.
        spoken_verses: One verse tuple per collapsed spoken run, in
            ``split.spoken`` order. Every source event is matched by style,
            visible text, and its run's timing bounds.
        dest: Output path (same format as the source).

    Raises:
        SubtitleError: The file could not be written.
    """
    if split.stats.total_events == 0:
        return None
    output = _translated_file(split, displayed_verses, spoken_verses)
    return _write_output(output, dest, split.kind, subject="Translated")


def write_translated_spoken(
    split: SubtitleSplit,
    spoken_verses: Sequence[tuple[str, ...]],
    dest: Path,
) -> Path | None:
    """Write the translated spoken-only subtitle product atomically."""
    if split.stats.spoken_events == 0:
        return None
    output = _translated_file(split, (), spoken_verses, selected="spoken")
    return _write_output(output, dest, split.kind, subject="Translated spoken")


def write_translated_displayed(
    split: SubtitleSplit,
    displayed_verses: Sequence[tuple[str, ...]],
    dest: Path,
) -> Path | None:
    """Write the translated displayed-only subtitle product atomically."""
    if split.stats.displayed_events == 0:
        return None
    output = _translated_file(split, displayed_verses, (), selected="displayed")
    return _write_output(output, dest, split.kind, subject="Translated displayed")
