"""Provider-neutral text-to-speech domain."""

from __future__ import annotations

from anishift.services.tts.config import TtsConfig
from anishift.services.tts.engines import TtsEngineId, available_engine_ids, create_engine
from anishift.services.tts.errors import (
    TtsAuthError,
    TtsCancelledError,
    TtsConfigError,
    TtsError,
    TtsInputError,
    TtsNetworkError,
    TtsProviderUnavailableError,
    TtsRateLimitError,
    TtsTimeoutError,
    TtsUnsupportedError,
    TtsVoiceError,
)
from anishift.services.tts.protocols import CancellationToken, TtsEngine
from anishift.services.tts.types import (
    AudioFormat,
    AvailabilityProbeKind,
    AvailabilitySource,
    AvailabilityStatus,
    EngineAvailability,
    EngineCapabilities,
    EngineClipResult,
    EngineLocality,
    EngineOptions,
    EngineOptionValue,
    ProcessArchitecture,
    SpeechBatch,
    SpeechBatchResult,
    SpeechBatchStats,
    SpeechBatchStatus,
    SpeechClip,
    SpeechPreparationStatus,
    SpeechRequest,
    SynthesisRequest,
    SynthesisStatus,
    SynthesizedRequest,
    VoiceInfo,
)

__all__ = [
    "AudioFormat",
    "AvailabilityProbeKind",
    "AvailabilitySource",
    "AvailabilityStatus",
    "CancellationToken",
    "EngineAvailability",
    "EngineCapabilities",
    "EngineClipResult",
    "EngineLocality",
    "EngineOptionValue",
    "EngineOptions",
    "ProcessArchitecture",
    "SpeechBatch",
    "SpeechBatchResult",
    "SpeechBatchStats",
    "SpeechBatchStatus",
    "SpeechClip",
    "SpeechPreparationStatus",
    "SpeechRequest",
    "SynthesisRequest",
    "SynthesisStatus",
    "SynthesizedRequest",
    "TtsAuthError",
    "TtsCancelledError",
    "TtsConfig",
    "TtsConfigError",
    "TtsEngine",
    "TtsEngineId",
    "TtsError",
    "TtsInputError",
    "TtsNetworkError",
    "TtsProviderUnavailableError",
    "TtsRateLimitError",
    "TtsTimeoutError",
    "TtsUnsupportedError",
    "TtsVoiceError",
    "VoiceInfo",
    "available_engine_ids",
    "create_engine",
]
