"""Public application contracts for callers independent of CLI and TUI."""

from importlib import import_module
from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    from anishift.application.acquisition import (
        AcquisitionService,
        CatalogOrder,
        ClientStatus,
        DownloadReceipt,
        EpisodeReading,
        ReleaseCatalog,
        ReleaseChoice,
        SeasonContext,
        SeriesGroup,
        order_groups,
        read_episode,
    )
    from anishift.application.automation import AutomationOwner
    from anishift.application.control_payloads import encode_intent
    from anishift.application.control_views import (
        PlanPreview,
        RunProgressSnapshot,
        decode_view,
        encode_view,
        preview_plan,
    )
    from anishift.application.discovery import (
        PRIMARY_SOURCE_SUFFIXES,
        DiscoveryResult,
        DiscoveryWarning,
    )
    from anishift.application.inspection import (
        InspectedSourceGroup,
        InspectedWorkspace,
        InspectionWarning,
        WorkspaceInspector,
    )
    from anishift.application.ready import ReadyStore
    from anishift.application.scheduler import RunHandle
    from anishift.application.service import (
        AppService,
        AutoPresetDraft,
        EnvironmentSettingStatus,
        ExecutionHandlerFactory,
        ModelAvailability,
        ModelProbeResult,
        SettingsDraft,
        TranslationModelOption,
    )
    from anishift.application.subscriptions import CHECK_INTERVAL_S as SUBSCRIPTION_CHECK_INTERVAL_S
    from anishift.application.subscriptions import (
        AiringSource,
        CheckOutcome,
        EpisodeOrder,
        EpisodeState,
        Subscription,
        SubscriptionEnd,
        SubscriptionOrder,
        SubscriptionService,
    )
    from anishift.application.watch_state import WATCH_STATE_FILE_NAME, WatchStateStore
    from anishift.services.catalog import TitleCandidate, TitleCatalogError, TitleStatus
    from anishift.services.torrents.query import EpisodeRange, SearchQuery, parse_query
    from anishift.setup.doctor import CheckResult
    from anishift.setup.installer import ResourceResult

from anishift.application.artifacts import (
    Artifact,
    ArtifactKind,
    ArtifactLifetime,
    ArtifactState,
    GroupConflict,
    GroupConflictKind,
    SourceGroup,
)
from anishift.application.cancellation import CancellationToken, EventCancellationToken
from anishift.application.control import (
    AcquisitionConfirmation,
    AcquisitionState,
    AutomationPolicy,
    CommandReceipt,
    ManualHandledMarker,
    ProcessingRequest,
    ProductConfirmation,
    ProviderLock,
    RefusalReason,
    RequestState,
    Reservation,
    SourceSelection,
    WatchState,
)
from anishift.application.events import (
    RunEvent,
    RunEventEmitter,
    RunEventKind,
    RunEventSink,
    WorkerNotification,
    WorkerNotificationKind,
)
from anishift.application.intents import (
    TRANSLATE_PRODUCTS,
    VIDEO_PRODUCTS,
    AutoPreset,
    BurnSubtitleProduct,
    ExternalAudioRole,
    GroupIntent,
    MkvTrackProduct,
    Mp4AudioSource,
    NarrationTimeline,
    ProductIntent,
    ProductKind,
    RebuildRequest,
    RequestOrigin,
    RunMode,
    SubtitleOutputFormat,
    SubtitleSourcePolicy,
    TranslationAction,
)
from anishift.application.planner import plan_auto, plan_manual
from anishift.application.planning import (
    ExecutionPlan,
    GroupPlan,
    PlanProblem,
    PlanTask,
    ProcessingOrderPolicy,
    RunSettingsSnapshot,
    TaskKind,
    TaskState,
)
from anishift.application.results import (
    ArtifactSnapshot,
    GroupResult,
    GroupStatus,
    ProducedArtifact,
    RunResult,
    TaskResult,
)
from anishift.application.selection import (
    GroupReadiness,
    ReadinessReason,
    group_is_ready,
    legal_narration_timelines,
    legal_products,
    ready_group_ids,
    resolve_readiness,
)
from anishift.application.watch import SCAN_INTERVAL_S, WatchLedger
from anishift.application.workflows import WorkflowTarget

__all__ = [
    "PRIMARY_SOURCE_SUFFIXES",
    "SCAN_INTERVAL_S",
    "SUBSCRIPTION_CHECK_INTERVAL_S",
    "TRANSLATE_PRODUCTS",
    "VIDEO_PRODUCTS",
    "WATCH_STATE_FILE_NAME",
    "AcquisitionConfirmation",
    "AcquisitionService",
    "AcquisitionState",
    "AiringSource",
    "AppService",
    "Artifact",
    "ArtifactKind",
    "ArtifactLifetime",
    "ArtifactSnapshot",
    "ArtifactState",
    "AutoPreset",
    "AutoPresetDraft",
    "AutomationOwner",
    "AutomationPolicy",
    "BurnSubtitleProduct",
    "CancellationToken",
    "CatalogOrder",
    "CheckOutcome",
    "CheckResult",
    "ClientStatus",
    "CommandReceipt",
    "DiscoveryResult",
    "DiscoveryWarning",
    "DownloadReceipt",
    "EnvironmentSettingStatus",
    "EpisodeOrder",
    "EpisodeRange",
    "EpisodeReading",
    "EpisodeState",
    "EventCancellationToken",
    "ExecutionHandlerFactory",
    "ExecutionPlan",
    "ExternalAudioRole",
    "GroupConflict",
    "GroupConflictKind",
    "GroupIntent",
    "GroupPlan",
    "GroupReadiness",
    "GroupResult",
    "GroupStatus",
    "InspectedSourceGroup",
    "InspectedWorkspace",
    "InspectionWarning",
    "ManualHandledMarker",
    "MkvTrackProduct",
    "ModelAvailability",
    "ModelProbeResult",
    "Mp4AudioSource",
    "NarrationTimeline",
    "PlanPreview",
    "PlanProblem",
    "PlanTask",
    "ProcessingOrderPolicy",
    "ProcessingRequest",
    "ProducedArtifact",
    "ProductConfirmation",
    "ProductIntent",
    "ProductKind",
    "ProviderLock",
    "ReadinessReason",
    "ReadyStore",
    "RebuildRequest",
    "RefusalReason",
    "ReleaseCatalog",
    "ReleaseChoice",
    "RequestOrigin",
    "RequestState",
    "Reservation",
    "ResourceResult",
    "RunEvent",
    "RunEventEmitter",
    "RunEventKind",
    "RunEventSink",
    "RunHandle",
    "RunMode",
    "RunProgressSnapshot",
    "RunResult",
    "RunSettingsSnapshot",
    "SearchQuery",
    "SeasonContext",
    "SeriesGroup",
    "SettingsDraft",
    "SourceGroup",
    "SourceSelection",
    "Subscription",
    "SubscriptionEnd",
    "SubscriptionOrder",
    "SubscriptionService",
    "SubtitleOutputFormat",
    "SubtitleSourcePolicy",
    "TaskKind",
    "TaskResult",
    "TaskState",
    "TitleCandidate",
    "TitleCatalogError",
    "TitleStatus",
    "TranslationAction",
    "TranslationModelOption",
    "WatchLedger",
    "WatchState",
    "WatchStateStore",
    "WorkerNotification",
    "WorkerNotificationKind",
    "WorkflowTarget",
    "WorkspaceInspector",
    "decode_view",
    "encode_intent",
    "encode_view",
    "group_is_ready",
    "legal_narration_timelines",
    "legal_products",
    "order_groups",
    "parse_query",
    "plan_auto",
    "plan_manual",
    "preview_plan",
    "read_episode",
    "ready_group_ids",
    "resolve_readiness",
]

_LAZY_EXPORTS: Final[dict[str, tuple[str, str]]] = {
    "PlanPreview": ("anishift.application.control_views", "PlanPreview"),
    "RunProgressSnapshot": ("anishift.application.control_views", "RunProgressSnapshot"),
    "decode_view": ("anishift.application.control_views", "decode_view"),
    "encode_intent": ("anishift.application.control_payloads", "encode_intent"),
    "encode_view": ("anishift.application.control_views", "encode_view"),
    "preview_plan": ("anishift.application.control_views", "preview_plan"),
    "PRIMARY_SOURCE_SUFFIXES": ("anishift.application.discovery", "PRIMARY_SOURCE_SUFFIXES"),
    "AppService": ("anishift.application.service", "AppService"),
    "AiringSource": ("anishift.application.subscriptions", "AiringSource"),
    "CheckOutcome": ("anishift.application.subscriptions", "CheckOutcome"),
    "EpisodeOrder": ("anishift.application.subscriptions", "EpisodeOrder"),
    "EpisodeState": ("anishift.application.subscriptions", "EpisodeState"),
    "SubscriptionEnd": ("anishift.application.subscriptions", "SubscriptionEnd"),
    "SubscriptionOrder": ("anishift.application.subscriptions", "SubscriptionOrder"),
    "WatchStateStore": ("anishift.application.watch_state", "WatchStateStore"),
    "ReadyStore": ("anishift.application.ready", "ReadyStore"),
    "WATCH_STATE_FILE_NAME": ("anishift.application.watch_state", "WATCH_STATE_FILE_NAME"),
    "AutomationOwner": ("anishift.application.automation", "AutomationOwner"),
    "RunHandle": ("anishift.application.scheduler", "RunHandle"),
    "SUBSCRIPTION_CHECK_INTERVAL_S": ("anishift.application.subscriptions", "CHECK_INTERVAL_S"),
    "Subscription": ("anishift.application.subscriptions", "Subscription"),
    "SubscriptionService": ("anishift.application.subscriptions", "SubscriptionService"),
    "AcquisitionService": ("anishift.application.acquisition", "AcquisitionService"),
    "CatalogOrder": ("anishift.application.acquisition", "CatalogOrder"),
    "EpisodeReading": ("anishift.application.acquisition", "EpisodeReading"),
    "SeasonContext": ("anishift.application.acquisition", "SeasonContext"),
    "read_episode": ("anishift.application.acquisition", "read_episode"),
    "EpisodeRange": ("anishift.services.torrents.query", "EpisodeRange"),
    "SearchQuery": ("anishift.services.torrents.query", "SearchQuery"),
    "parse_query": ("anishift.services.torrents.query", "parse_query"),
    "TitleCandidate": ("anishift.services.catalog", "TitleCandidate"),
    "TitleCatalogError": ("anishift.services.catalog", "TitleCatalogError"),
    "TitleStatus": ("anishift.services.catalog", "TitleStatus"),
    "AutoPresetDraft": ("anishift.application.service", "AutoPresetDraft"),
    "ClientStatus": ("anishift.application.acquisition", "ClientStatus"),
    "DownloadReceipt": ("anishift.application.acquisition", "DownloadReceipt"),
    "ReleaseCatalog": ("anishift.application.acquisition", "ReleaseCatalog"),
    "ReleaseChoice": ("anishift.application.acquisition", "ReleaseChoice"),
    "SeriesGroup": ("anishift.application.acquisition", "SeriesGroup"),
    "order_groups": ("anishift.application.acquisition", "order_groups"),
    "EnvironmentSettingStatus": ("anishift.application.service", "EnvironmentSettingStatus"),
    "CheckResult": ("anishift.setup.doctor", "CheckResult"),
    "DiscoveryResult": ("anishift.application.discovery", "DiscoveryResult"),
    "DiscoveryWarning": ("anishift.application.discovery", "DiscoveryWarning"),
    "InspectedSourceGroup": ("anishift.application.inspection", "InspectedSourceGroup"),
    "InspectedWorkspace": ("anishift.application.inspection", "InspectedWorkspace"),
    "InspectionWarning": ("anishift.application.inspection", "InspectionWarning"),
    "ExecutionHandlerFactory": ("anishift.application.service", "ExecutionHandlerFactory"),
    "ModelAvailability": ("anishift.application.service", "ModelAvailability"),
    "ModelProbeResult": ("anishift.application.service", "ModelProbeResult"),
    "ResourceResult": ("anishift.setup.installer", "ResourceResult"),
    "SettingsDraft": ("anishift.application.service", "SettingsDraft"),
    "TranslationModelOption": ("anishift.application.service", "TranslationModelOption"),
    "WorkspaceInspector": ("anishift.application.inspection", "WorkspaceInspector"),
}
"""I/O exports loaded only when requested, avoiding eager package import cycles."""


def __getattr__(name: str) -> object:
    """Load controlled-I/O facade objects without making every submodule eager."""
    target: tuple[str, str] | None = _LAZY_EXPORTS.get(name)
    if target is None:
        msg = f"module {__name__!r} has no attribute {name!r}"
        raise AttributeError(msg)
    module_name, attribute_name = target
    value: object = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value
